# Generated by Django 3.2.9 on 2024-05-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.BigIntegerField(default=100),
        ),
    ]
