# Generated by Django 3.2.9 on 2024-05-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
