# Generated by Django 3.2.9 on 2024-05-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userquizstatistic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquizstatistic',
            old_name='correct_answers',
            new_name='user_answers',
        ),
    ]
